name: CI

on:
  push:
    branches:
    - master

env:
  PROJECT: angular
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# TODO: pin actions
jobs:
  image:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ env.PROJECT }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: ${{ env.PROJECT }}/package-lock.json

    - name: Run clean install
      run: npm ci

    - name: Run tests
      run: npm test -- --browsers ChromeHeadless --no-watch --no-progress

    - name: Build the project
      run: npm run build -- --configuration production

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }} as ${{ github.actor }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push the image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
